spring:
  application:
    name: greeting-microservice
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-microservice:
  greeting: "Olá, tudo bem?"
  default-value: "Sim! Bem vindo!!"